In [1]:
from pprint import pprint
from pybea.client import BureauEconomicAnalysisClient
import json
import pandas as pd

In [2]:
bea_client = BureauEconomicAnalysisClient(api_key='64C1A606-C86B-4702-A5D0-977F79A936D1')

In [5]:
SAGDP6N = bea_client.regional(
    table_name=['SAGDP6N'],
    line_code=1,
    geo_fips=['STATE'],
    year=['LAST10']
)

https://apps.bea.gov/api/data/?userid=64C1A606-C86B-4702-A5D0-977F79A936D1&method=GetData&datasetname=Regional&year=LAST10&TableName=SAGDP6N&GeoFips=STATE&LineCode=1&resultformat=JSON

In [7]:
SAGDP6Ndata = (SAGDP6N['BEAAPI']['Results']['Data'])

In [8]:
SAGDP6Ndf = pd.DataFrame(SAGDP6Ndata)
SAGDP6Ndf

,Code,GeoFips,GeoName,TimePeriod,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,SAGDP6N-1,00000,United States *,2011,Thousands of dollars,3,"1,103,725,000",*
1,SAGDP6N-1,00000,United States *,2012,Thousands of dollars,3,"1,136,117,000",*
2,SAGDP6N-1,00000,United States *,2013,Thousands of dollars,3,"1,188,662,000",*
3,SAGDP6N-1,00000,United States *,2014,Thousands of dollars,3,"1,240,830,000",*
4,SAGDP6N-1,00000,United States *,2015,Thousands of dollars,3,"1,275,152,000",*
...,...,...,...,...,...,...,...,...
595,SAGDP6N-1,98000,Far West,2016,Thousands of dollars,3,"243,784,485",NaN
596,SAGDP6N-1,98000,Far West,2017,Thousands of dollars,3,"254,659,733",NaN
597,SAGDP6N-1,98000,Far West,2018,Thousands of dollars,3,"278,777,909",NaN
598,SAGDP6N-1,98000,Far West,2019,Thousands of dollars,3,"304,034,039",NaN
599,SAGDP6N-1,98000,Far West,2020,Thousands of dollars,3,"296,635,432",NaN

In [11]:
SAGDP6N_2 = bea_client.regional(
    table_name=['SAGDP6N'],
    line_code=3,
    geo_fips=['STATE'],
    year=['LAST10']
)

https://apps.bea.gov/api/data/?userid=64C1A606-C86B-4702-A5D0-977F79A936D1&method=GetData&datasetname=Regional&year=LAST10&TableName=SAGDP6N&GeoFips=STATE&LineCode=3&resultformat=JSON

In [12]:
SAGDP6N_2data = (SAGDP6N_2['BEAAPI']['Results']['Data'])
SAGDP6N_2df = pd.DataFrame(SAGDP6N_2data)
SAGDP6N_2df

,Code,GeoFips,GeoName,TimePeriod,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,SAGDP6N-3,00000,United States *,2011,Thousands of dollars,3,"9,532,000",*
1,SAGDP6N-3,00000,United States *,2012,Thousands of dollars,3,"9,830,000",*
2,SAGDP6N-3,00000,United States *,2013,Thousands of dollars,3,"10,247,000",*
3,SAGDP6N-3,00000,United States *,2014,Thousands of dollars,3,"11,626,000",*
4,SAGDP6N-3,00000,United States *,2015,Thousands of dollars,3,"10,862,000",*
...,...,...,...,...,...,...,...,...
595,SAGDP6N-3,98000,Far West,2016,Thousands of dollars,3,"1,846,567",NaN
596,SAGDP6N-3,98000,Far West,2017,Thousands of dollars,3,"2,017,437",NaN
597,SAGDP6N-3,98000,Far West,2018,Thousands of dollars,3,"2,150,298",NaN
598,SAGDP6N-3,98000,Far West,2019,Thousands of dollars,3,"2,213,629",NaN
599,SAGDP6N-3,98000,Far West,2020,Thousands of dollars,3,"2,301,590",NaN