In [1]:
from pprint import pprint
from pybea.client import BureauEconomicAnalysisClient
import json
import pandas as pd

In [2]:
bea_client = BureauEconomicAnalysisClient(api_key='64C1A606-C86B-4702-A5D0-977F79A936D1')

In [3]:
SAPCE2 = bea_client.regional(
    table_name=['SAPCE2'],
    line_code=1,
    geo_fips=['STATE'],
    year=['LAST10']
)

https://apps.bea.gov/api/data/?userid=64C1A606-C86B-4702-A5D0-977F79A936D1&method=GetData&datasetname=Regional&year=LAST10&TableName=SAPCE2&GeoFips=STATE&LineCode=1&resultformat=JSON

In [4]:
SAPCE2data = (SAPCE2['BEAAPI']['Results']['Data'])
SAPCE2df = pd.DataFrame(SAPCE2data)
SAPCE2df

         Code GeoFips        GeoName TimePeriod  CL_UNIT UNIT_MULT DataValue
0    SAPCE2-1   00000  United States       2011  Dollars         0    34,337
1    SAPCE2-1   00000  United States       2012  Dollars         0    35,196
2    SAPCE2-1   00000  United States       2013  Dollars         0    35,954
3    SAPCE2-1   00000  United States       2014  Dollars         0    37,212
4    SAPCE2-1   00000  United States       2015  Dollars         0    38,235
..        ...     ...            ...        ...      ...       ...       ...
595  SAPCE2-1   98000       Far West       2016  Dollars         0    41,553
596  SAPCE2-1   98000       Far West       2017  Dollars         0    43,489
597  SAPCE2-1   98000       Far West       2018  Dollars         0    45,746
598  SAPCE2-1   98000       Far West       2019  Dollars         0    47,710
599  SAPCE2-1   98000       Far West       2020  Dollars         0    45,788

[600 rows x 7 columns]